skipwords: NOT_FOUND
id_match: '^MGI:\d+$'


lists:
    MY-LIST-1:
        file: ../example_output/example_7_output.txt
        column: 1
        skip_title: 1 
        table:
        pubmed:
        year: 2011
        species: mouse
        description: Genes from example 7 
        confidential: no

    MY-LIST-2:
        file: ../data/my_list_of_genes_2.txt
        column: 1
        skip_title: 1 
        table:
        pubmed:
        year: 2011
        species: mouse
        description: Genes from experiment 2
        confidential: no
