#!/usr/local/bin/perl
### nomenclature

=pod

=head1 NAME - add_approved_name_by_mgi_id

=head1 COMMAND LINE PARAMETERS 

Required parameters
  --file                        file to be processed
  --mgi_id_column               column containing MGI IDs (>= 1)
  --output_column               column to output added names (>= 1)
  
Optional parameters
  --skip_title                  skip first (title) row
    
=head1 DESCRIPTION

Adds the approved (protein) name to a tabular file by using data parsed
from the MGI nomenclature file 'MRK_List2.rpt' which should be in the
directory pointed to by $ENV{MGI_dir}

Look-up is done by the MGI ID e.g. MGI:95819; this example being  
called 'glutamate receptor, ionotropic, NMDA1 (zeta 1)'

=head1 AUTHOR - mike_croning@hotmail.com

=cut 

use strict;
use warnings;
use Carp;
use GeneNomenclatureUtils::TabFileParser qw(
    show_perldoc
);
use GeneNomenclatureUtils::SeqIDNomenclature qw(
    check_or_translate_ids_in_file
    parse_mgi_list_2_file
);   

use Data::Dumper;
use Getopt::Long;

{
    print STDERR "\n$0\n", '=' x length($0), "\n\n";
    my ($file, $mgi_column, $output_column, $skip_title);
        
    GetOptions(
        "file=s"              => \$file,
        "mgi_id_column=i" => \$mgi_column,
        "output_column=i"     => \$output_column,
        "skip_title"          => \$skip_title,
    ) or show_perldoc();
    show_perldoc("Must set --file") unless $file;
    unless ($mgi_column and $mgi_column >= 1) {
        show_perldoc("Must set --mgi_id_column >= 1");
    }
    
    unless ($output_column and $output_column >= 1) {
        show_perldoc("Must set --output_column >= 1");
    }
    
    ### Parse nomenclature files
    my ($parsed_by_mgi_symbol, $parsed_by_mgi_id, $approved_name_by_mgi_id)
        = parse_mgi_list_2_file();
        
    ### Do the translation
    check_or_translate_ids_in_file($file, $approved_name_by_mgi_id, 'Appr. NAME'
        , '^MGI:\d+$', $mgi_column, $output_column, $skip_title, 'translate');
}
