#!/usr/local/bin/perl
### nomenclature

=pod

=head1 NAME - add_mgi_id_by_mgi_symbol

=head1 COMMAND LINE PARAMETERS

Required parameters
  --file                    file to be processed                
  --mgi_symbol_column       column number with MGI Symbols (>= 1)
  --output_column           column to output the added IDs (>= 1)
  
  
Optional parameters
  --skip_title              skip title row

=head1 DESCRIPTION

Adds MGI IDs (eg. MGI:1888986) to a tab-delimited file, by MGI SYMBOL
e.g. Dlg3.

Looks for the nomenclature file called 'MRK_List2.sql.rpt' in the
directory pointed to by $ENV{MGI_dir}

Outputs to STDOUT

Example command line

./add_mgi_id_by_mgi_symbol --file=/nfs/file.txt --mgi_symbol_column=1
--output_column=1 --skip_title

This will prepend a column to the file with the requested IDs.

=head1 AUTHOR - mike_croning@hotmail.com

=cut 

use strict;
use warnings;
use Carp;
use GeneNomenclatureUtils::Parser;
use GeneNomenclatureUtils::TabFileParser qw(
    show_perldoc
);
use Getopt::Long;

{
    print STDERR "\n$0\n", '=' x length($0), "\n\n";
    my ($file, $mgi_column, $output_column, $skip_title);
        
    GetOptions(
        "file=s"              => \$file,
        "mgi_symbol_column=i" => \$mgi_column,
        "output_column=i"     => \$output_column,
        "skip_title"          => \$skip_title,
    ) or show_perldoc();

    ### Check we have the correct parameters
    unless ($file) {
        show_perldoc('Must set --file');
    }
    unless ($mgi_column and $mgi_column >= 1) {
        show_perldoc('Must set --mgi_symbol_column >= 1');
    }
    unless ($output_column and $output_column >= 1) {
        show_perldoc('Must set --output_column >= 1');
    }

    ### Setup parser
    my $parser = GeneNomenclatureUtils::Parser->new(
        'MGI_dir', 'MRK_List2.rpt', 'symbol');
    $parser->add_filter('type', 'nomatch', 'Gene');    
    $parser->parse;

    ### Output attributes
    $parser->output_attribute('mgi_accession_id');
    $parser->file_process_mode('translate');

    ### Convert
    $parser->process_file($file, $mgi_column, $output_column
        , $skip_title,  'MGI ID');
}
