#!/software/bin/perl
### nomenclature

=pod

=head1 NAME - check_rgd_ids

=head1 COMMAND LINE PARAMETERS

Required parameters
  --file                    file to be checked                
  --rgd_id_column           column containing IDs to check (>= 1)
  --output_column           column to output results (>=1 ) 
  
Optional parameters
  --skip_title              skip first (title) row

=head1 DESCRIPTION

Checks RGD IDs, eg. 68423 for the gene Dlg3 in a tab-delimited file

Utilises the nomenclature file called 'GENES_RAT.txt' in the
directory pointed to by $ENV{RGD_dir}

Output to STDOUT

Example command line

./check_rgd_ids --file=my_file.txt --rgd_id_column=1
--skip_title --output_column=1 > my_output.txt

This will prepend a column to the file with the results of the
check.

=head1 AUTHOR - mike_croning@hotmail.com

=cut 

use strict;
use warnings;
use Carp;
use DPStore::Utils::SeqIDNomenclature qw(
    check_or_translate_ids_in_file
);   
use GeneNomenclatureUtils::Parser;
use GeneNomenclatureUtils::TabFileParser qw(
    show_perldoc
);
use Getopt::Long;

{
   print STDERR "\n$0\n", '=' x length($0), "\n\n";
   my ($file, $rgd_id_column, $output_column, $skip_title);
        
    GetOptions(
        "file=s"              => \$file,
        "rgd_id_column=i"     => \$rgd_id_column,
        "output_column=i"     => \$output_column,
        "skip_title"          => \$skip_title,
    ) or show_perldoc();
    show_perldoc("Must set --file") unless $file;
    unless ($rgd_id_column and $rgd_id_column >= 1) {
        show_perldoc("Must set --rgd_id_column >= 1");
    }
    unless ($output_column and $output_column >= 1) {
        show_perldoc("Must set --output_column >= 1");
    }

    my $parser = GeneNomenclatureUtils::Parser->new(
        'RGD_dir', 'GENES_RAT.txt', 'gene_rgd_id');
    $parser->output_attribute('gene_rgd_id'); #Parser needs one specified
    $parser->file_process_mode('check');
    $parser->parse;
        
    $parser->process_file($file, $rgd_id_column, $output_column
        , $skip_title, 'RGD ID CHECK');

=cut
    ### Do the check
    check_or_translate_ids_in_file($file, $parser, 'RGD ID CHECK'
        , undef, $rgd_id_column, $output_column, $skip_title);
=cut

}
