#!/software/bin/perl
### nomenclature

=pod

=head1 NAME - check_hgnc_ids

=head1 COMMAND LINE PARAMETERS

Required parameters
  --file                    file to be checked                
  --hgnc_id_column          column containing IDs to check (>= 1)
  --output_column           column to output results (>= 1)
  
Optional parameters
  --skip_title              skip first (title) row

=head1 DESCRIPTION

Checks HGNC IDs (eg. HGNC:4584) in the specified column of 
a tab-delimited text file

Outputs to STDOUT

Example command line

./check_hgnc_ids --file=my_file.txt --hgnc_id_column=1
--skip_title --output_column=1 > my_output.txt

This will prepend a column to the file with the results of the
check.

=head1 AUTHOR - mike_croning@hotmail.com

=cut 

use strict;
use warnings;
use Carp;
use GeneNomenclatureUtils::Parser;
use GeneNomenclatureUtils::SeqIDNomenclature qw(
    check_or_translate_ids_in_file
    parse_hgnc_core_file
);   
use GeneNomenclatureUtils::TabFileParser qw(
    show_perldoc
);

use Getopt::Long;

{
   print STDERR "\n$0\n", '=' x length($0), "\n\n";
   my ($file, $hgnc_id_column, $output_column, $skip_title);
        
    GetOptions(
        "file=s"              => \$file,
        "hgnc_id_column=i"    => \$hgnc_id_column,
        "output_column=i"     => \$output_column,
        "skip_title"          => \$skip_title,
    ) or show_perldoc();

    ### Check we have the correct parameters
    unless ($file) {
        show_perldoc('Must set --file');
    }
    unless ($hgnc_id_column and $hgnc_id_column >= 1) {
        show_perldoc("Must set --hgnc_id_column >= 1");
    }
    unless ($output_column and $output_column >= 1) {
        show_perldoc("Must set --output_column >= 1");
    }

    ### Setup parser
    my $parser = GeneNomenclatureUtils::Parser->new(
        'HGNC_dir', 'hgnc_core_data.txt', 'hgnc_id');
    
    #Excludes status !~ /Approved/      
    $parser->add_filter('status', 'nomatch', 'Approved'); 
    $parser->prepend_key('HGNC:');
    $parser->prepend_attribute('hgnc_id', 'HGNC:');
    $parser->parse;

    ### Output attributes
    $parser->output_attribute('hgnc_id'); #Parser needs one specified
    $parser->file_process_mode('check');

    ### Convert
    $parser->process_file($file, $hgnc_id_column, $output_column
        , $skip_title,  'HGNC ID CHECK');
}
