#!/software/bin/perl
### nomenclature

=pod

=head1 NAME - extract_entrez_gene_info_by_tax_id

=head1 COMMAND LINE PARAMETERS 

Required parameters
  --tax_id                  taxonomy ID

=head1 DESCRIPTION

Extracts from the Entrez Gene file 'gene_info' by taxonomy ID.

ftp://ftp.ncbi.nih.gov/gene/DATA/gene_info.gz

Common taxonomy IDs
  9606    human
  10090   mouse

=head1 AUTHOR - mike_croning@hotmail.com

=cut

use strict;
use warnings;
use Carp;
use GeneNomenclatureUtils::TabFileParser qw(
    close_data_files
    open_data_file
    read_next_line_from_data_file
    show_perldoc
);
use Getopt::Long;

{
    print STDERR "\n$0\n", '=' x length($0), "\n\n";
    my ( $tax_id );
    GetOptions(
        "tax_id=i"                => \$tax_id,
    ) or show_perldoc();
    unless ($tax_id) {
        show_perldoc("Must set --tax_id");
    }
    unless ($ENV{'ENTREZ_dir'}) {
        show_perldoc('Must set $ENV{ENTREZ_dir}');
    }

    my $file = $ENV{'ENTREZ_dir'} . '/gene_info';
    unless (-e $file) {
        confess "Could not read: '$file'\n";
    }
    
    my $count = 0;
    open_data_file('gene', $file);
    while (my $line = read_next_line_from_data_file('gene')) {
        if ($line =~ /^$tax_id\t/) {
            print $line;
            $count++;
        }
    }
    close_data_files();
        
    print STDERR "$count genes for $tax_id\n";
}
