#!/usr/local/bin/perl
### nomenclature

=pod

=head1 NAME - remove_trailing_whitespace

=head1 COMMAND LINE PARAMETERS 

  --file            file to pe processed

=head1 DESCRIPTION

Removes trailing white space from lines in a tab_delimited 
file. 

=head1 AUTHOR - mike_croning@hotmail.com

=cut

use strict;
use warnings;
use Carp;
use GeneNomenclatureUtils::TabFileParser qw(
    parse_tab_delimited_file_to_array
    show_perldoc
);   
use Data::Dumper;
use Getopt::Long;

{
    print STDERR "\n$0\n", '=' x length($0), "\n\n";
    my ($file);
        
    GetOptions(
        "file=s"          => \$file,
    ) or show_perldoc();
    show_perldoc("Must set --file") unless $file;
    
    my $data = parse_tab_delimited_file_to_array($file, 'clean');

    my $line_count = 0;
    foreach my $entry (@$data) {

        my $line = join("\t", @$entry);
        $line =~ s/\w+$//;
        print join("\t", @$entry);
		print "\n";        
    }
    
    print STDERR "Line: count: $line_count\n";    
} 
